- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Test/CoreTests/ItemViewRepoTests.cs
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Test/CoreTests/SampleItemsSearchRepoTests.cs
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Test/WebTests/ControllerTests/ItemsSearchControllerTests.cs
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Controllers/ItemsSearchController.cs
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Startup.cs
Controller tests and core tests have been templated for future use and all tests are passing.
> Feature controller testing

- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Dal/Providers/Models/ItemDigest.cs
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Dal/Translations/ItemDigestTranslation.cs
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Dal/Xml/Models/ItemXmlFieldRepresentation.cs
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Test/DalTests/TranslationsTests/ItemDigestTranslationTests.cs
> Added item type to item digest and translation models (#18)

- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Scripts/ItemPage.tsx
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Scripts/ShareModal.tsx
Fix for the '&' character in ISAAP codes breaking urls.
> Feature uri encode isaap

- SmarterBalanced.SampleItems/InteractionTypeConfigurations/InteractionTypes.xml
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Scripts/AboutItems.tsx
Updated About Item page to include line breaks, shows all types of Grid Items
> Feature about item

- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Styles/item.less
> Updated more like this modal to show all columns on the same row

- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Test/DalTests/TranslationsTests/ItemDigestTranslationTests.cs
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Test/DalTests/TranslationsTests/StandardIdentifierTranslationTests.cs
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Test/DalTests/XmlTests/StandardIdentifierEqualityTests.cs
Finished StandardIdentifierTranslationTests
> Feature test updates

- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Styles/nav.less
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Styles/search.less
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Styles/site.less
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Views/Shared/_Layout.cshtml
Fixes that make both IE and Chrome happy
> Feature header fix

- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Core/Repos/AboutItemsRepo.cs
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Core/Repos/IAboutItemsRepo.cs
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Core/Repos/IItemViewRepo.cs
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Core/Repos/ItemViewRepo.cs
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Core/Repos/Models/AboutItemsViewModel.cs
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Test/DalTests/XmlTests/StandardIdentifierEqualityTests.cs
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Test/WebTests/ControllerTests/AboutItemsControllerTests.cs
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Controllers/AboutItemsController.cs
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Scripts/AboutItems.tsx
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Styles/about.less
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Views/AboutItems/Index.cshtml
Adds "About This Item" modal to About Items page, resolves #136
> Feature about items about this item modal

- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Views/Home/Index.cshtml
> homepage wording update

- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Dal/Translations/StandardIdentifierTranslation.cs
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Test/DalTests/TranslationsTests/StandardIdentifierTranslationTests.cs
Fixes naming typo on publications to identifier translation
> Feature claims translation

- .travis.yml
- DeployScripts/runEcsBuild.sh
updates travis to push to docker
> updated travis script, ecsbuild script

- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Controllers/HomeController.cs
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Views/Home/Index.cshtml
cache ivs scripts on homepage to speed up item loading.
> Feature iframe caching

- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Core/Repos/ItemViewRepo.cs
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Dal/Providers/Models/GradeLevels.cs
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Scripts/MoreLikeThisModal.tsx
removes NA column, changes high school grade numbers to "high school"
> MoreLikeThis updates

- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Scripts/AccessibilityModal.tsx
> Disabled Designated Support and Accommodations

- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Dal/Translations/AccessibilityResourceTranslation.cs
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Test/DalTests/TranslationsTests/AccessibilityTranslationTests.cs
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Controllers/HomeController.cs
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Scripts/ItemsSearchParams.tsx
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Styles/search.less
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Views/Home/Index.cshtml
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Views/Shared/_Layout.cshtml
> removed homepage prefetch iframe, changes nav bar text

- .travis.yml
- DeployScripts/runEcsBuild.sh
> Travis branch problems

- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Controllers/ItemController.cs
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Scripts/Braille.tsx
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Styles/item.less
When a user clicks the download link for braille files a spinner appears until the download starts.
> Add animation for braille zip file download

- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Scripts/AccessibilityModal.tsx
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Scripts/DropDown.tsx
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Scripts/ItemCard.tsx
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Scripts/ItemPage.tsx
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Styles/search.less
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Styles/site.less
Fixes for using a screen reader with the website.
> Feature sr fixes

- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Dal/Providers/Models/GradeLevels.cs
> Grade level enum now returns highschool for grades 9-12

- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Controllers/BrowseItemsController.cs
Downloads to csv
Use BrowseItems/ExportItems to download
> added ExportItems to download items as .csv

- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Scripts/ItemCard.tsx
Item cards are static and do not need to be updated
> Implement shouldComponentUpdate

- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Test/CoreTests/ReposTests/ItemViewRepoTests.cs
- SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web/Controllers/BrowseItemsController.cs
* utf-8 encoding fix for .csv
* test fix for GetAboutThisItemViewModel
* site.css itemviewer-iframe fix for outer scroll bar
> Feature test update
